### ISSUE TITLE
Confusion about the number of novel predicates

### ISSUE THREAD

**Issue by jkli1998** [SHTUPLUS/Pix2Grp_CVPR2024#5]
Thanks again for sharing this nice work. 
I have another question regarding the number of novel predicates.

Section 5.1 in this paper states that 50% of the predicates were randomly selected as NOVEL categories. And Supporting Material A (Datasets and tasks) states that 30% were selected as the NOVEL class. So how many predicates were selected as the NOVEL class? Which part of the code reflected this selection?

**Comment by Scarecrow0** [comment]
We use the  50% of the predicates were randomly selected as novel class.

**Comment by jkli1998** [comment]
Thanks for your reply, but i found `zs_predicate` in `vrd_vg_ft_pgsg_ov.yaml` contains 30 categories while VG contains 50 categories. It seems the ratio is 60%?

**Comment by jkli1998** [comment]
The same question for PSG dataset. The `zs_predicate` in `vrd_psg_ft_pgsg_ov.yaml` contains 16 categories while PSG contains 56 categories.

**Comment by kongzihan** [comment]
> Thanks for your reply, but i found `zs_predicate` in `vrd_vg_ft_pgsg_ov.yaml` contains 30 categories while VG contains 50 categories. It seems the ratio is 60%?

I also encountered the same problem. In the code, zs_predicate contains 30 categories, accounting for 60% of the total 50. I am confused about the division of predicates. Sincerely looking forward to your reply.

**Comment by Scarecrow0** [comment]
Thank you very much for your interest in our work.
 
I have re-checked the division of relevant categories in the experiment. In our work, the Visual Genome dataset selected 60% of the categories as novel classes, while the Open Image and PSG datasets respectively adopted 30% of the categories as novel classes. The specific IDs of the divided categories are all presented in the config of the codebase.
 
Due to my negligence, the specific division ratio was not clearly stated in the paper. I will update the ratio of the novel class of each dataset in the arXiv paper in a timely manner as soon as possible. For the subsequent experiments, please refer to the actual code. 
Sorry for the trouble caused to you.

**Comment by jkli1998** [comment]
Thanks for your reply! I got it.
And thank you for your contribution in the field of scene graph generation :)
